openapi: 3.0.3
info:
  title: О нас API
  description: API для отображения страницы "О нас"
  version: 1.0.0
servers:
  - url: http://localhost:8090/api
    description: Основной сервер

components:
  responses:
    NotFound:
      description: Страница не найдена
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 404</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 404 - Страница не найдена</h2>
                  <p>Запрашиваемая страница не существует.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    MethodNotAllowed:
      description: Метод не поддерживается
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 405</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 405 - Метод запроса не поддерживается.</h2>
                  <p>Запрашиваемая страница не существует.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 500</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 500 - Внутренняя ошибка сервера</h2>
                  <p>На сервере произошла ошибка. Пожалуйста, попробуйте позже.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    BadRequest:
      description: Неверный запрос
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 400</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 400 - Неправильный запрос</h2>
                  <p>Обращение некорректно.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

paths:
  /about-us:
    get:
      summary: Страница "О нас"

      responses:
        '200':
          description: Данные успешно обновлены
          content:
            text/html:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /kontakts:
    get:
      summary: Страница "Контакты"

      responses:
        '200':
          description: Получение html страницы "Контакты"
          content:
            text/html:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
