openapi: 3.0.3
info:
  title: Пользовательское API
  description: API для управления пользователями и восстановления пароля.
  version: 1.0.0
servers:
  - url: http://localhost:8090/api/user
    description: Основной сервер

security:
  - basicAuth: []

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    UpdateUserRequest:
      type: object
      properties:
        nickname:
          type: string
          description: Никнейм пользователя
        Password:
          type: string
          description: Новый пароль пользователя
        SuccessPassword:
          type: string
          description: Подтверждение нового пароля
      required:
        - nickname
        - Password
        - SuccessPassword

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Ошибка при выполнении операции."

  responses:
    NotFound:
      description: Страница не найдена
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 404</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 404 - Страница не найдена</h2>
                  <p>Запрашиваемая страница не существует.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    Forbidden:
      description: Доступ запрещен
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 403</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 403 - Доступ запрещен</h2>
                  <p>У вас нет прав для доступа к этой странице.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    MethodNotAllowed:
      description: Метод не поддерживается
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 405</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 405 - Метод запроса не поддерживается.</h2>
                  <p>Запрашиваемая страница не существует.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    UnsupportedMediaType:
      description: Неподдерживаемый тип носителя
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 415</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 415 - Неподдерживаемый тип носителя.</h2>
                  <p>Формат содержимого не поддерживается сервером.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 500</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 500 - Внутренняя ошибка сервера</h2>
                  <p>На сервере произошла ошибка. Пожалуйста, попробуйте позже.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

    BadRequest:
      description: Неверный запрос
      content:
        text/html:
          schema:
            type: string
            example: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8; default-src 'self'; script-src 'self' 'unsafe-hashes'" />
                <script type="text/javascript" src="/js/jquery-3.7.1.slim.min.js"></script>
                <link href="/css/style.css" rel="stylesheet" />
                <link href="/css/bootstrap.min.css" rel="stylesheet" />
                <script type="text/javascript" src="/js/body.js"></script>
                <script type="text/javascript" src="/js/bootstrap.bundle.min.js"></script>
              
                <title>Ошибка 400</title>
                <meta http-equiv="Content-Security-Policy" content="script-src 'none'; default-src 'self';">
                <link href="/css/registrationSuccess.css" rel="stylesheet" />
              </head>
              <body>
                <div class="container">
                  <h2>Ошибка 400 - Неправильный запрос</h2>
                  <p>Обращение некорректно.</p>
                  <a href="/api/kanban/menu">Вернуться на главную</a>
                </div>
              </body>
              </html>

paths:
  /update:
    post:
      summary: Обновление данных пользователя
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
        required: true
      responses:
        '200':
          description: Данные успешно обновлены
          content:
            text/plain:
              schema:
                type: string
                example: "Данные успешно обновлены."
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /forgot-password:
    post:
      summary: Восстановление пароля
      description: Отправляет ссылку для сброса пароля на электронную почту пользователя, которая привязана к текущей сессии.
      responses:
        '200':
          description: Письмо отправлено успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Новый пароль отправлен на Вашу почту."
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'

  /forgot-password-with-email:
    post:
      summary: Восстановление пароля по электронной почте
      parameters:
        - name: email
          in: query
          description: Электронная почта пользователя
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ссылка для сброса пароля отправлена
          content:
            text/plain:
              schema:
                type: string
                example: "Новый пароль отправлен на Вашу почту."
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '500':
          $ref: '#/components/responses/InternalServerError'
