@startuml
skinparam style strictuml
hide empty members

rectangle "FlexiKanban" as "FlexiKanban" {
    class "Пользователь" {
        Почта
        Имя
        Пароль
        Статус активности
        Проверка заблокированости
        Роль
    }

    class "Проект" {
        Название
        Проверка удаления
    }

    class "Канбан-задача" {
        Название
        Описание
        Статус
    }

    class "Кано-задача" {
        Название
        Описание
        Статус
    }

    class "MoSCoW-задача" {
        Название
        Описание
        Статус
    }

    class "Подтверждение регистрации" {
        Токен
        Дата создания
        Дата Подтверждения
        Дата истечения срока действия
    }

    class "Приглашение" {
        Кто пригласил
        Кого пригласили
        Куда пригласили
        Статус активности
    }

    class "Подтвержденные приглашения" {
        Токен
        Кто пригласил
        Кого пригласили
        Куда пригласили
        Дата создания
        Дата Подтверждения
        Дата истечения срока действия
    }
}

Проект -left- Пользователь
Проект -right- "Канбан-задача"
Проект -down- "Кано-задача"
Проект -down- "MoSCoW-задача"

"Подтверждение регистрации" -right- Пользователь
"Подтвержденные приглашения" -up- Пользователь
"Подтвержденные приглашения" -up- Пользователь
"Подтвержденные приглашения" -up- Проект

"Приглашение" -down- Пользователь
"Приглашение" -down- Пользователь
"Приглашение" -down- Проект

@enduml