@startuml

package "FlexiKanban" {
    package "Меню" {
        package "Проект" {
            [Доска]

            [Кано-задачи]

            interface КаноAPI
            КаноAPI )-- [Кано-задачи] : "Обработка операций"

            [MoSCoW-задачи]

            interface MoSCoWAPI
            MoSCoWAPI )-- [MoSCoW-задачи] : "Обработка операций"

            [Канбан-задачи]

            interface КанбанAPI
            КанбанAPI )-- [Канбан-задачи] : "Обработка операций"

            [Доска] -- КанбанAPI : "CRUD запросы"
            [Доска] -- MoSCoWAPI : "CRUD запросы"
            [Доска] -- КаноAPI : "CRUD запросы"
        }

        [Меню-канбан]

        interface МенюAPI

        [Меню-канбан] -- МенюAPI : "CRUD запросы"

        МенюAPI )-- [Доска] : "Обработка операций"
    }

    package "Данные сайта" {
        package "pdf" {
            [Пользовательское соглашение]
            [Политика об обработке персональных данных]
        }

        [О нас]
        [Контакты]
    }

    [О нас] -down- "Получить 'О нас'"
    [Контакты] -down- "Получить 'Контакты'"
    [Пользовательское соглашение] -down- "Получить 'Пользовательское соглашение'"
    [Политика об обработке персональных данных] -down- "Получить 'Политика об обработке персональных данных'"

    package "Пользователь" {
        package "Аутентификаця" {
            [Авторизация]
            [Регистрация]
            [Выход из системы]
        }

        [токен]
        [Профиль]
        [Токен приглашения]
    }

    [Почта]

    component Почта {
        port Письмо
    }

    [Авторизация] .down.> [Почта] :"Забыли пароль"
    [Профиль] .down.> [Почта] :"Забыли пароль"
    [Регистрация] .down.> [Почта] :"Подтверждение почты"
    [Меню-канбан] .down.> [Почта] :"Приглашение"

    [Авторизация] -- Сессия : "Вход"

    Сессия <.down. [Профиль] : авторизация обязательна
    Сессия <.. [Доска] : авторизация обязательна
    Сессия ..> [Авторизация] : перенаправление
    Сессия ..> [токен] : проверка токена
    Сессия <.. [MoSCoW-задачи] : авторизация обязательна
    Сессия <.. [Кано-задачи] : авторизация обязательна
    Сессия <.. [Канбан-задачи] : авторизация обязательна

    Сессия -- [Выход из системы] : "Выход"
}

Письмо -down- gmail
[токен] -up-( gmailConfirm : "Подтверждение регистрации"
[Профиль] -down-( inviteToDesc : "Подтверждение приглашения"
[Токен приглашения] -down( inviteToDesc : "Подтверждение приглашения"

@enduml