@startuml
'https://plantuml.com/state-diagram
skinparam style strictuml
hide empty members

scale 350 width
[*] --> Страница_Входа : C0
[*] --> Страница_О_Нас : C1
[*] --> Страница_Контакты : C2
[*] --> Страница_Регистрации : C3

Страница_Входа --> Страница_Входа : C4
Страница_Входа -down-> Страница_О_Нас : C5
Страница_Входа -right-> Страница_Контакты : C6
Страница_Входа -down-> Страница_Регистрации : C7
Страница_Входа -up-> Меню : C8

Страница_О_Нас --> Страница_О_Нас : C9
Страница_О_Нас --> Страница_Входа : C10
Страница_О_Нас --> Страница_Регистрации : C11
Страница_О_Нас --> Страница_Контакты : C12
Страница_О_Нас --> Страница_Профиля : C13

Страница_Контакты --> Страница_О_Нас : C14
Страница_Контакты --> Страница_Входа : C15
Страница_Контакты --> Страница_Регистрации : C16
Страница_Контакты --> Страница_Контакты : C17
Страница_Контакты --> Страница_Профиля : C18

Страница_Регистрации --> Страница_О_Нас : C19
Страница_Регистрации --> Страница_Входа : C20
Страница_Регистрации --> Страница_Регистрации : C21
Страница_Регистрации --> Страница_Контакты : C22
Страница_Регистрации --> Подтвердите_Почту : C23
Подтвердите_Почту --> Страница_Регистрации : C24
Страница_Регистрации --> Страница_Регистрации : C25

Страница_Профиля --> Меню : C26
Страница_Профиля --> Страница_О_Нас : C27
Страница_Профиля --> Страница_Контакты : C28
Страница_Профиля --> Страница_Профиля : C29

state Меню {
    Страница_Меню --> Страница_Меню : C30
    Страница_Меню --> Страница_Меню_Модальное_Окно_Подтверждения_Удаления : C31
    Страница_Меню_Модальное_Окно_Подтверждения_Удаления --> Страница_Меню : C32
    Страница_Меню_Модальное_Окно_Подтверждения_Удаления --> Страница_Меню : C33
    Страница_Меню --> Страница_Меню_Модальное_Окно_Изменения : C34
    Страница_Меню_Модальное_Окно_Изменения --> Страница_Меню : C35
    Страница_Меню_Модальное_Окно_Изменения --> Страница_Меню : C36
    Страница_Меню --> Приглашение_Пользователя : C37
    Приглашение_Пользователя --> Страница_Меню : C38
    Страница_Меню --> Страница_Канбан_Доски : C39

    Страница_Канбан_Доски -down-> Страница_Канбан_Доски_Модальное_Окно_Добавления_Задачи : C44
    Страница_Канбан_Доски_Модальное_Окно_Добавления_Задачи --> Страница_Канбан_Доски : C45
    Страница_Канбан_Доски_Модальное_Окно_Добавления_Задачи --> Страница_Канбан_Доски : C46
    Страница_Канбан_Доски -down-> Страница_Канбан_Доски_Модальное_Окно_Изменения_Задачи : C47
    Страница_Канбан_Доски_Модальное_Окно_Изменения_Задачи --> Страница_Канбан_Доски : C48
    Страница_Канбан_Доски_Модальное_Окно_Изменения_Задачи --> Страница_Канбан_Доски : C49
    Страница_Канбан_Доски -down-> Страница_Канбан_Доски : C50

    Страница_Канбан_Доски --> Страница_Кано_Доски : C51

    Страница_Кано_Доски -down-> Страница_Кано_Доски_Модальное_Окно_Добавления_Задачи : C52
    Страница_Кано_Доски_Модальное_Окно_Добавления_Задачи --> Страница_Кано_Доски : C53
    Страница_Кано_Доски_Модальное_Окно_Добавления_Задачи --> Страница_Кано_Доски : C54
    Страница_Канбан_Доски -down-> Страница_Кано_Доски_Модальное_Окно_Изменения_Задачи : C55
    Страница_Кано_Доски_Модальное_Окно_Изменения_Задачи --> Страница_Кано_Доски : C56
    Страница_Кано_Доски_Модальное_Окно_Изменения_Задачи --> Страница_Кано_Доски : C57
    Страница_Кано_Доски -down-> Страница_Кано_Доски : C58

    Страница_Канбан_Доски --> Страница_MoSCoW_Доски : C59

    Страница_MoSCoW_Доски -down-> Страница_MoSCoW_Доски_Модальное_Окно_Добавления_Задачи : C60
    Страница_MoSCoW_Доски_Модальное_Окно_Добавления_Задачи --> Страница_MoSCoW_Доски : C61
    Страница_MoSCoW_Доски_Модальное_Окно_Добавления_Задачи --> Страница_MoSCoW_Доски : C62
    Страница_MoSCoW_Доски -down-> Страница_MoSCoW_Доски_Модальное_Окно_Изменения_Задачи : C63
    Страница_MoSCoW_Доски_Модальное_Окно_Изменения_Задачи --> Страница_MoSCoW_Доски : C64
    Страница_MoSCoW_Доски_Модальное_Окно_Изменения_Задачи --> Страница_MoSCoW_Доски : C65
    Страница_MoSCoW_Доски -down-> Страница_MoSCoW_Доски : C66

    Страница_Канбан_Доски --> Страница_Канбан_Доски : C67
    Страница_Кано_Доски --> Страница_Кано_Доски : C68
    Страница_MoSCoW_Доски --> Страница_MoSCoW_Доски : C69

    Страница_Канбан_Доски --> Страница_Канбан_Доски : C70

    Страница_Кано_Доски --> Страница_Кано_Доски : C71
    Страница_Кано_Доски --> Страница_Канбан_Доски : C72
    Страница_Кано_Доски --> Страница_MoSCoW_Доски : C73

    Страница_MoSCoW_Доски --> Страница_Канбан_Доски : C74
    Страница_MoSCoW_Доски --> Страница_MoSCoW_Доски : C75
    Страница_MoSCoW_Доски --> Страница_Кано_Доски : C76

    Страница_Канбан_Доски --> Страница_Меню : C77
    Страница_Канбан_Доски --> Страница_Профиля : C78
    Страница_Канбан_Доски --> Страница_Контакты : C79
    Страница_Канбан_Доски --> Страница_О_Нас : C80

    Страница_Кано_Доски --> Страница_Меню : C81
    Страница_Кано_Доски --> Страница_Профиля : C82
    Страница_Кано_Доски --> Страница_Контакты : C83
    Страница_Кано_Доски --> Страница_О_Нас : C84

    Страница_MoSCoW_Доски --> Страница_Меню : C85
    Страница_MoSCoW_Доски --> Страница_Профиля : C86
    Страница_MoSCoW_Доски --> Страница_Контакты : C87
    Страница_MoSCoW_Доски --> Страница_О_Нас : C88
}

Страница_Входа -up-> Страница_Входа_Модальное_Окно_Ошибки : C40
Страница_Входа_Модальное_Окно_Ошибки --> Страница_Входа : C41
Страница_Входа -up-> Страница_Входа_Модальное_Окно_Подтверждения_Выполнения : C42
Страница_Входа_Модальное_Окно_Подтверждения_Выполнения --> Страница_Входа : C43

Страница_Канбан_Доски --> [*] : C89
Страница_Кано_Доски --> [*] : C90
Страница_MoSCoW_Доски --> [*] : C91
Меню --> [*] : C92
Страница_Профиля --> [*] : C93
Страница_Контакты --> [*] : C94
Страница_О_Нас --> [*] : C95

@enduml